# Generated by Django 4.0.4 on 2022-05-31 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='publicated_at',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='publicated_at',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_admin',
            new_name='is_admin',
        ),
    ]
